version = 5.7.0
archive_dir = /etc/letsencrypt/archive/hethongchothuemayanh.com
cert = /etc/letsencrypt/live/hethongchothuemayanh.com/cert.pem
privkey = /etc/letsencrypt/live/hethongchothuemayanh.com/privkey.pem
chain = /etc/letsencrypt/live/hethongchothuemayanh.com/chain.pem
fullchain = /etc/letsencrypt/live/hethongchothuemayanh.com/fullchain.pem
[renewalparams]
account = bafc35478e49b1820e7afc1e0f9ffeba
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
hethongchothuemayanh.com = /var/www/certbot
www.hethongchothuemayanh.com = /var/www/certbot
[acme_renewal_info]
ari_retry_after = 2026-09-02T02:50:48
